Login/markup
caulipse/caulipse-ui pull request #139
Opened 2022-03-10 15:45 UTC by tngur1101

Conflict 또 나는지 확인 부탁드려요

2022-03-10 15:46 UTC, Jeyoung-Park commented
> Conflict 또 나는지 확인 부탁드려요

conflict 나는지 여부는 현재 브랜치에서 실행시켰을 때 에러 나는지 보고 판단해 주시면 됩니다
다음부터 올리기 전에 한 번 확인하고 올려주세요 :)

2022-03-10 15:52 UTC, Jeyoung-Park commented on src/app/login/boxContainer/LoginBoxContainer.tsx
> +         [name]: value,
input에 name이 없는데 이렇게 되면 값이 원하는 대로 들어가지 않을 것 같네요

2022-03-10 15:53 UTC, Jeyoung-Park commented on src/app/login/boxContainer/LoginBoxContainer.tsx
> +                <button type="button" id="login-btn">로그인</button>
오호 위에서는 className을 사용하시고 여기서는 id를 사용하시는 이유가 있으신가요?

2022-03-10 15:54 UTC, Jeyoung-Park commented on src/app/login/boxContainer/boxcontainer.scss
> +  margin: 3rem 12% 3rem;
다른 데서는 margin 고정 값으로 되어 있는데 여기는 %로 되어 있네요 %로 사용하는 게 맞는지 확인 한 번 부탁드려요!

2022-03-10 15:54 UTC, Jeyoung-Park commented on src/app/login/footercontainer/FooterContainer.scss
> +  line-height: 1.36;
여기 단위가 빠진 것 같네요

2022-03-10 15:55 UTC, Jeyoung-Park commented on src/app/login/footercontainer/FooterContainer.scss
> +  margin-left: 90vh;
vh는 높이에 비례하는 값인데 marginleft 값으로 쓰이는 게 맞을까요?

2022-03-10 15:57 UTC, Jeyoung-Park commented on src/app/login/footercontainer/FooterContainer.scss
> +  margin: 0 1.156rem 0 0;
사소한 내용이긴 한데 이런 경우에는 margin-right와 같이 쓰는 게 더 가독성이 좋아보일 수도 있을 것 같네요. 이건 취향차이라고 생각해서 반영 하셔도 되고 안 하셔도 될 듯 합니다

2022-03-10 15:58 UTC, Jeyoung-Park commented on src/app/login/loginLogo/Logins.tsx
> +            <div>
여기를 이중으로 감싸신 이유가 있으신가요?

2022-03-10 15:59 UTC, Jeyoung-Park commented on src/app/login/loginLogo/Logins.tsx
> +import './LoginLogo.scss';
여기 파일명이 Logins.tsx네요 컴포넌트 이름이랑 같이 가져가면 다른 팀원들이 이해하기 좀 더 편할 것 같아요!

2022-03-10 16:05 UTC, Jeyoung-Park commented on src/app/modal/StudyFilterModal.tsx
> -const StudyFilterModal = ({ open, onClose }: IModalContainerCommonProps): JSX.Element => {
수혁님 여기 부분 삭제되면 안 될 거 같은데요. 미리님 작업하신 부분인데 확인 한 번 부탁드려요

2022-03-10 16:06 UTC, Jeyoung-Park commented on src/app/signup/boxcontainer/BoxContainer.tsx
> +import React, {useState} from "react";
위에 LoginBoxContainer랑 중복되는 파일이 있는 것 같네요 확인 부탁드려요~

2022-03-10 16:09 UTC, Jeyoung-Park commented on src/app/signup/signupid/SignupId.tsx
> +                <span className="NickName">닉네임</span>
className은 class-name과 같이 네이밍 붙이도록 네이밍 컨벤션이 지정되어 있습니다. 위에 파일에도 그런 부분들이 있는데 그렇게 되어 있는 부분은 수정 부탁드려요~

2022-03-10 16:10 UTC, Jeyoung-Park commented on src/app/signup/signuplogo/SignupLogo.tsx
> +
여기 띄어쓰기 되어 있는 이유는 있나요?

2022-03-10 16:13 UTC, Jeyoung-Park commented on src/app/signup/signupid/SignupId.tsx
> +                    <option value="1학년">1학년</option>
value값은 서버에서 사용하는 value type과 맞추면 좋을 것 같습니다.

2022-03-10 16:13 UTC, Jeyoung-Park commented on src/app/signup/signupid/SignupId.tsx
> +                    <option value="재학중">재학중</option>
여기도 서버에서 사용하는 타입과 맞추면 좋겠네요

2022-03-10 16:14 UTC, Jeyoung-Park commented on src/app/study/modal/studyFilterModal/StudyFilterModalContainer.tsx
> +import React, { ChangeEvent, useState, useEffect } from 'react';
수혁님 이거는 삭제된 파일인데 포함되었네요. 확인 부탁드려요

2022-03-10 16:15 UTC, Jeyoung-Park commented on src/pages/signup/index.tsx
> +            {/* <div className="Signup-Btn">
이 주석은 왜 들어간 건가요?

2022-03-10 16:15 UTC, Jeyoung-Park commented on src/pages/signup/index.tsx
> +import { IoCloseOutline } from 'react-icons/io5';
수혁님 저희 지난 회의 떄 OutLine 들어간 거 말고 일반 아이콘만 사용하기로 합의했었습니다. 참고 부탁드려요~

2022-03-10 17:34 UTC, tngur1101 commented on src/pages/signup/index.tsx
> +import { IoCloseOutline } from 'react-icons/io5';
아 이거 conflict하면서 수정한게 날라간것같아요 ㅠㅠ

2022-03-10 23:57 UTC, taechonkim commented on src/app/login/boxContainer/LoginBoxContainer.tsx
> +
@tngur1101 수혁님! 인덴트나 세미콜론 여부를 봤을 때 IDE 에 프리티어 설정이 제대로 안 되어 있는 것 같습니다 ;_;

2022-03-11 00:00 UTC, taechonkim commented on src/app/login/footercontainer/FooterContainer.scss
> +  font-family: NotoSansKR;
@tngur1101 기본 폰트가 notosanskr 이어서 font family 는 따로 작성하시지 않아도 될것같습니다!

2022-03-14 12:55 UTC, tngur1101 commented on src/app/signup/signupid/SignupId.tsx
> +                    <option value="재학중">재학중</option>
서버에서 사용하는 타입은 어떻게 확인하나요?

2022-03-14 14:01 UTC, tngur1101 commented on src/app/signup/signupid/SignupId.tsx
> +                <span className="NickName">닉네임</span>
이게 어떤 뜻인가요?

2022-03-14 14:46 UTC, Jeyoung-Park commented on src/app/signup/signupid/SignupId.tsx
> +                    <option value="재학중">재학중</option>
@tngur1101 서버 쪽에서 보내주신 문서 확인하거나 아니면 직접 값 받아서 확인해 보시면 됩니다. 여기 값은 boolean 값으로 되어 있는데 일단 고치기 어려우시면 나중에 서버 값 받을 때 고치시죠~

2022-03-14 14:48 UTC, Jeyoung-Park commented on src/app/signup/signupid/SignupId.tsx
> +                <span className="NickName">닉네임</span>
className이 NickName이 아니라 nickname과 같은 형태로 작업되어야 합니다
아래는 추가적인 컨벤션 예시입니다.
ex) nickname, my-nickname,  my-nickname-container

2022-03-14 14:49 UTC, Jeyoung-Park commented
@tngur1101 아 추가적으로 신경쓰셔야할 게 있을 것 같습니다. 이 부분은 추후 작업하실 때 챙겨주세요!
1. 저희가 mui 라이브러리 써서 작업하고 있어서 마크업 작업하실 때 이 라이브러리 사용해 주시면 통일감 있게 작업이 될 듯 합니다. 저도 작업한 부분 이걸로 조금씩 바꾸면서 하고 있어서 참고 부탁드려요!
2. 로그인 부분이 팝업으로 된 걸로 알고 있는데 다음 pr 때 이 부분도 작업해서 pr 올려주시면 감사드리겠습니다
3. pr 길이가 길어서 리뷰가 많이 쌓인 것 같은데 pr 짧게 짧게 끊어서 올려주시면 리뷰하기도 편하고 수혁 님께서 반영하시기도 편할 듯 합니다. 참고 부탁드려요!

2022-03-14 14:51 UTC, Jeyoung-Park requested changes
@tngur1101 아 추가적으로 신경쓰셔야할 게 있을 것 같습니다. 이 부분은 추후 작업하실 때 챙겨주세요!
1. 저희가 mui 라이브러리 써서 작업하고 있어서 마크업 작업하실 때 이 라이브러리 사용해 주시면 통일감 있게 작업이 될 듯 합니다. 저도 작업한 부분 이걸로 조금씩 바꾸면서 하고 있어서 참고 부탁드려요!
2. 로그인 부분이 팝업으로 된 걸로 알고 있는데 다음 pr 때 이 부분도 작업해서 pr 올려주시면 감사드리겠습니다
3. pr 길이가 길어서 리뷰가 많이 쌓인 것 같은데 pr 짧게 짧게 끊어서 올려주시면 리뷰하기도 편하고 수혁 님께서 반영하시기도 편할 듯 합니다. 참고 부탁드려요!

일단 저랑 미리님께서 남긴 코멘트 확인해 주시고 반영 부탁드리겠습니다 🙏

2022-03-17 14:05 UTC, closed without merging