Feat/redux toolkit
caulipse/caulipse-ui pull request #18
Opened 2021-12-07 14:04 UTC by Jeyoung-Park

- redux toolkit에 대한 기본적인 작업을 진행했습니다.
- redux logger를 추가했습니다.

@taechonkim @seonghyeoncho @tngur1101 
api 받아오는 부분은 서버 측에서 api 작업 완료되면 services 폴더 생성한 뒤에 rtk-query 이용해서 작업할 계획입니다. api 나오기 전에 먼저 작업하는 게 좋을 것 같다고 의견 주시면 먼저 작업해서 반영하겠습니다.
이 pr에서는 redux toolkit에 대한 간단한 구조만 잡고 있습니다. module은 user 부분만 간단하게 추가되어있는데 필요할 때마다 추가해서 사용하면 어떨까 싶습니다

2021-12-07 14:07 UTC, Jeyoung-Park commented on src/store/modules/user.ts
> +	userInfo: any;
user module 부분은 다음 pr 때 구체적으로 작업하기 위해 일단은 any로 타입을 선언했습니다. 참고해주시면 감사드리겠습니다 🙏

2021-12-08 07:55 UTC, seonghyeoncho requested changes

2021-12-08 07:55 UTC, seonghyeoncho commented on package.json
>      "jotai": "0.16.3",
저희 redux-toolkit으로 정해졌으니까 jotai에 관한 부분은 의존성 삭제해도 될 것 같아요

2021-12-08 07:55 UTC, seonghyeoncho commented on src/store/modules/user.ts
> +	userInfo: any;
넵넵

2021-12-08 17:10 UTC, Jeyoung-Park commented on package.json
>      "jotai": "0.16.3",
@seonghyeoncho 적용했습니다!

2021-12-08 17:51 UTC, seonghyeoncho approved these changes

2021-12-08 17:53 UTC, merged