Feat/study detail
caulipse/caulipse-ui pull request #24
Opened 2021-12-13 06:58 UTC by seonghyeoncho

study detail에 관한 기능들을 작성했습니다
계속 작업중이긴 한데 좀 많아질 것 같아서 미리 열어두겠습니다

2021-12-13 15:10 UTC, Jeyoung-Park commented
성현님 추후에 작업하시는 부분 이 브랜치에 푸시하실 건가요? 아니면 머지하시고 추가로 pr 올리실 건가요?

2021-12-13 15:13 UTC, Jeyoung-Park commented on src/app/shared/components/input/InputBaseContainer.tsx
> +    </div>
여기 div 태그로 한 번 더 감싸신 이유는 추후에 확장성을 고려하신 건가요?

2021-12-13 15:30 UTC, Jeyoung-Park requested changes

2021-12-13 15:30 UTC, Jeyoung-Park commented on src/app/studyDetail/studyContent/StudyContentContainer.tsx
> +  const [study, setStudy] = useState<GetStudyResponse>();
아래에서 useEffect를 사용해 값을 넣는 것도 좋지만 useState의 초기값에 값을 넣는 방법은 어떤지 제안드립니다.
```typescript
  const [study, setStudy] = useState<GetStudyResponse>(studyData);
```
아니면 state를 선언하지 않고 props로 넘겨받은 studyData를 그대로 사용하는 건 어떨지 제안드립니다.

2021-12-13 15:30 UTC, Jeyoung-Park commented on src/app/studyDetail/studyContent/StudyContentContainer.tsx
> +    if (i === 1) return <StudyInfoContentContainer study={study!}/>
오호 ts의 Non-null assertion operator에 대해 오늘 처음 알았습니다!

2021-12-13 15:30 UTC, Jeyoung-Park commented on src/app/studyDetail/studyContent/currentState/StudyCurrentStateContainer.tsx
> +    <StudyCurrentStatePresenter host={hostD} studyUsers={studyUser} />
D는 data를 의미하시는 거죠? 네이밍에 관해 고려할 때 snake case, camel case 정도의 레벨만 생각했었는데 변수에서 줄임말을 사용할지, 사용한다면 어디까지 사용할지 이런 것도 컨벤션으로 정하면 좋을까요?
정해놓으면 좋을 것 같긴 한데 작업 속도가 많이 더뎌질 거 같아 고민이 되네요 ㅠ

2021-12-13 15:30 UTC, Jeyoung-Park commented on src/app/studyDetail/studyInfo/StudyInfoPresenter.tsx
>        <div className="categoty">카테고리</div>
여기 category 오타있습니다

2021-12-13 15:30 UTC, Jeyoung-Park commented on src/app/studyDetail/studyInfo/StudyInfoPresenter.tsx
> +        <span>{study.categoryCode}</span>
span 태그가 불필요하지 않나하는 생각이 듭니다!

2021-12-13 15:30 UTC, Jeyoung-Park commented on src/scss/_variables.scss
> +$BodyBackgroundColor: #F2F3F5;
아 저도 컬러코드 여기다 지정해서 사용해야겠네요 StudyDetailContentTextColor, StudyDetailTitleTextColor와 같이 겹치는 색들은 themeColor를 지정하는 것처럼 묶어서 사용하는 게 좋을까요? 
만약 컬러를 하나하나 일일히 지정해준다면 해당 css에서 선언해서 사용하는 편이 나아보입니다.
공통적으로 사용되는 primary, secondary, tertiary 정도는 지정해서 사용하면 좋을 것 같아요
이 부분은 프론트팀이랑 디자인 팀 시험 끝나고 여유로울 때 논의해보면 좋을 것 같네요!

2021-12-14 06:30 UTC, seonghyeoncho commented on src/app/studyDetail/studyContent/currentState/StudyCurrentStateContainer.tsx
> +    <StudyCurrentStatePresenter host={hostD} studyUsers={studyUser} />
Dummy의 의미로 사용한 부분입니다 일단어차피 지워질 부분이고 빠른 작업을 위해서 임의로 변수이름 지정했어요

2021-12-14 06:31 UTC, seonghyeoncho commented on src/app/studyDetail/studyContent/StudyContentContainer.tsx
> +  const [study, setStudy] = useState<GetStudyResponse>();
useEffect를 쓴 부분은 이제 비동기 처리 될 부분인데, 이 부분들은 store로 처리될 부분들로 생각하고 작성했습니다

2021-12-14 06:33 UTC, seonghyeoncho commented on src/app/studyDetail/studyContent/StudyContentContainer.tsx
> +  const [study, setStudy] = useState<GetStudyResponse>();
비동기 처리될 부분들의 로직을 어떻게 만들지는 얘기해봐야 할 것 같아요

저 부분에 loding이 있는 부분이 비동기의 역할을 임의로 수행하는 부분입니다

2021-12-14 06:38 UTC, seonghyeoncho commented on src/app/shared/components/input/InputBaseContainer.tsx
> +    </div>
원래 계획은 base로 interface 형태로 둔 다음 impl의 형태로 다형성을 만드려고 한 부분입니다. 어디서 쓰일 지는 잘 모르지만 일단 그렇게 작업해두는게 좋을 것 같아서요

근데 일단 지금 다형성 작업은 안해둬서 저렇게 남아있습니다 ㅋㅋㅋ

2021-12-14 06:38 UTC, seonghyeoncho commented on src/app/studyDetail/studyInfo/StudyInfoPresenter.tsx
> +        <span>{study.categoryCode}</span>
넵넵

2021-12-14 06:38 UTC, seonghyeoncho commented on src/scss/_variables.scss
> +$BodyBackgroundColor: #F2F3F5;
컬러 코드 네이밍도 정하면 좋을 것 같아요

 겹치는 부분들을 나중에 변동성을 생각해서 통일성이 있는 부분들은 따로 만들고 그게 아닌 부분들은 따로 만드는게 좋을 것 같다고 생각해서 일단은 같은 컬러 코드라도 각각 명시했습니다!

2021-12-14 06:39 UTC, seonghyeoncho commented
이 브렌치에 계속 푸쉬할 예정입니다

이 브렌치에서 필요하시다면 먼저 머지를 하고 진행하는 것도 좋을 것 같아요

2021-12-14 15:10 UTC, Jeyoung-Park commented on src/app/studyDetail/studyContent/StudyContentContainer.tsx
> +  const [study, setStudy] = useState<GetStudyResponse>();
아하 그렇군요 이 부분은 api 나온 이후에 한 번 더 살펴보면 좋을 것 같네요!

2021-12-14 15:12 UTC, Jeyoung-Park approved these changes
resolve되지 않는 부분들(오타와 같은 문제들)만 수정하시고 머지하셔도 될 것 같아요
pr이 너무 길면 관리하기 힘드니 여기서 한 번 머지하는 게 좋을 것 같습니다
고생 많으셨습니다 👍

2021-12-24 15:04 UTC, merged